name: JarvisMobile
options:
  bundleIdPrefix: tr.umitkalender
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
targets:
  JarvisMobile:
    type: application
    platform: iOS
    sources:
      - path: JarvisMobile
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: tr.umitkalender.jarvis
        PRODUCT_NAME: Jarvis
        PRODUCT_MODULE_NAME: JarvisMobile
        INFOPLIST_FILE: JarvisMobile/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
    scheme:
      testTargets:
        - JarvisMobileTests
  JarvisMobileUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: JarvisMobileUITests
    dependencies:
      - target: JarvisMobile
    settings:
      base:
        TEST_TARGET_NAME: JarvisMobile

  JarvisMobileTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: JarvisMobileTests
    dependencies:
      - target: JarvisMobile
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Jarvis.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Jarvis"
        BUNDLE_LOADER: "$(TEST_HOST)"
